Ingredient.create!(name: "lemon")
Ingredient.create!(name: "rice")
Ingredient.create!(name: "milk")
Ingredient.create!(name: "cucumber")
Ingredient.create!(name: "bread")
Ingredient.create!(name: "basil")
Ingredient.create!(name: "chickpeas")
